#Minecraft server properties
online-mode=false
difficulty=peaceful
spawn-protection=0
max-players=5
motd=Azalea Lab Server
enable-command-block=true
allow-flight=true
white-list=false
enforce-whitelist=false
gamemode=survival
level-name=world
server-port=25565
