modLoader = "lowcodefml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "checkpacketpatch"
version = "1.0.0"
displayName = "CheckPacket Patch"
description = "Patches NetworkRegistry.checkPacket to allow non-NeoForge clients"
